# Generated by Django 2.2 on 2019-07-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_coordinator',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='process',
        ),
    ]
